List<Map<String, String>> jokes = [
  {"title": "Skeleton", "joke": "No guts."},
  {"title": "Eyebrow", "joke": "Too high!"},
  {"title": "Gym", "joke": "No workout."},
  {"title": "Piano", "joke": "Hands only."},
  {"title": "Seafood", "joke": "See food."},
  {"title": "Coffee", "joke": "Adulting needs it."},
  {"title": "Math", "joke": "Absolute love."},
  {"title": "Doctor", "joke": "Laughter cure."},
  {"title": "Cow", "joke": "Moon walk."},
  {"title": "Bicycle", "joke": "Two-tired."},
  {"title": "Chicken", "joke": "Crossing road."},
  {"title": "Pizza", "joke": "Never disliked."},
  {"title": "Computer", "joke": "Too many bytes."},
  {"title": "Fish", "joke": "Afraid of net."},
  {"title": "Bread", "joke": "Knead break."},
  {"title": "Light", "joke": "Electric humor."},
  {"title": "Banana", "joke": "Bunch friends."},
  {"title": "Elephant", "joke": "Squash game."},
  {"title": "Snowman", "joke": "Melted joke."},
  {"title": "Vampire", "joke": "Blood orange."},
];
